version: 0.1.{build}
environment:
  matrix:
    - COMPILER: msys2
      PLATFORM: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
      BIT: 64
      PYTHON_DIR: Python33-x64
    - COMPILER: msys2
      PLATFORM: x86
      MSYS2_ARCH: i686
      MSYS2_DIR: msys64
      MSYSTEM: MINGW32
      BIT: 64
      PYTHON_DIR: Python33
    - COMPILER: msys2
      PLATFORM: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
      BIT: 64
      PYTHON_DIR: Python34-x64
    - COMPILER: msys2
      PLATFORM: x86
      MSYS2_ARCH: i686
      MSYS2_DIR: msys64
      MSYSTEM: MINGW32
      BIT: 64
      PYTHON_DIR: Python34
    - COMPILER: msys2
      PLATFORM: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
      BIT: 64
      PYTHON_DIR: Python35-x64
    - COMPILER: msys2
      PLATFORM: x86
      MSYS2_ARCH: i686
      MSYS2_DIR: msys64
      MSYSTEM: MINGW32
      BIT: 64
      PYTHON_DIR: Python35
    - COMPILER: msys2
      PLATFORM: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
      BIT: 64
      PYTHON_DIR: Python36-x64
    - COMPILER: msys2
      PLATFORM: x86
      MSYS2_ARCH: i686
      MSYS2_DIR: msys64
      MSYSTEM: MINGW32
      BIT: 64
      PYTHON_DIR: Python36
build_script:
  - C:\%PYTHON_DIR%\python.exe -m pip install --upgrade pip setuptools wheel
  - SET "PATH=C:\%MSYS2_DIR%\%MSYSTEM%\bin;C:\%MSYS2_DIR%\usr\bin;%PATH%"
  - bash -lc "pacman -S --needed --noconfirm pacman-mirrors"
  - bash -lc "pacman -S --needed --noconfirm git"
  - bash -lc "pacman -Syu --noconfirm"
  - bash -lc "pacman -S --needed --noconfirm make"
  - bash -lc "pacman -S --needed --noconfirm mingw-w64-%MSYS2_ARCH%-toolchain mingw-w64-%MSYS2_ARCH%-cmake mingw-w64-%MSYS2_ARCH%-openblas"
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
  - bash -lc "cd $APPVEYOR_BUILD_FOLDER; /c/%PYTHON_DIR%/python.exe setup.py build_ext"
  - bash -lc "cd $APPVEYOR_BUILD_FOLDER; /c/Python36-x64/python.exe setup.py bdist_wheel"
  - bash -lc "cd $APPVEYOR_BUILD_FOLDER; /c/%PYTHON_DIR%/python.exe setup.py install"
test_script:
  - cd %APPVEYOR_BUILD_FOLDER%
  - C:\%PYTHON_DIR%\python.exe tests/test_itensor.py
